import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./Components/SideBar";
import Header from "./Components/Header";
import { TeamProvider } from "../Context/TeamContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TeamProvider>
          <div className="flex flex-col">
            <header>
              <Header />
            </header>
            <div className="flex flex-1">
              <aside>
                <SideBar />
              </aside>
              {children}
            </div>
          </div>
        </TeamProvider>
      </body>
    </html>
  );
}
